#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=CorruptedDataEval
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=output_slurm/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate ir_env

papermill /home/scur1950/assignment2-neural-ir-team13/neural_ir_colab_evaluate.ipynb /home/scur1950/assignment2-neural-ir-team13/output_slurm/neural_ir_colab_evaluate_output.ipynb